### ISSUE TITLE
Deprecation warnings Dart Sass 3.0.0

### ISSUE THREAD

**Issue by Crossed-Omega** [sylhare/Type-on-Strap#470] opened 2024-11-17 21:54 UTC
Upon using ```bundle exec jekyll serve``` the generator emits many warnings about the deprecation of the @import system in Dart Sass.
```
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
1 │ @import "type-on-strap";
  │         ^^^^^^^^^^^^^^^
  ╵
    C:\Users\Windows-PC\Documents\Coding\Jekyll\type-on-strap\Type-on-Strap\assets\css\main.scss 1:9  root stylesheet
```

[The webpage linked by Sass](https://sass-lang.com/documentation/breaking-changes/import/) has an automatic migrator that can be ran over the style sheets with
```
$ npm install -g sass-migrator
$ sass-migrator module --migrate-deps your-entrypoint.scss
```
or, alternatively on Windows, downloading the dart executable and running (dry run and normal run emit the same exception)
```
.\sass-migrator module --migrate-deps -n C:\Users\Windows-PC\Documents\Coding\Jekyll\type-on-strap\Type-on-Strap\assets\css\main.scss
```

This however yields an exception that complains about an element miss in a list. Fairly sure that this is a bug on Sass-migrators' side.

Obviously, it would be nice to fix the deprecation warnings so as to not clutter the generation output, as well as future stability.

**Comment by sylhare** [comment] 2024-11-18 14:26
I think the problem is from the GitHub Page gem which does not support the most recent `jekyll-sass-converter`.
cf: https://github.com/github/pages-gem/issues/813

If I wear to update, not sure how compatible it will be as a GitHub page.

**Comment by Crossed-Omega** [comment] 2024-11-18 15:14
Hmm, fair. Is this a roadblock that needs to be cleared from GitHub Pages' side or is manual conversion possible? I use GitLab pages, I am fairly sure they have different compatibilities.

**Comment by sylhare** [comment] 2024-11-20 21:27
From the link https://sass-lang.com/documentation/breaking-changes/import/ it says:
> We’re deprecating both Sass @import rules and global built-in functions now that the module system (@use and @forward rules) has been available **for several years.**

So the new way might be compatible with the older `jekyll-sass-converter` 🤔 
I can try it out, see if I can do the migration and make it work.

**Comment by sylhare** [comment] 2024-11-26 14:37
@Crossed-Omega good news! After digging into how to migrate and remove the deprecated scss notation, it seems that there's no problem running it with the current version of `jekyll-sass-converter` 🙌 

I had to run the sass migration on the fontawesome lib still, but now there's no more warning that I can see.
I'll close the issue, thanks for flagging it up.

**Comment by sylhare** [comment] 2024-11-26 15:00
I think the best fix, I can provide is to quiet the warnings for now 🤔 Once the github page uses the latest converter, I'll push the sass update.

**Comment by sylhare** [comment] 2024-11-27 14:25
With #478 I can remove all but one warnings for the sass. I guess that's the max I can do for now.

**Closed** 2024-11-27 14:25 UTC
Labels: dependencies, fix
