### ISSUE TITLE
Math does't get centered

### ISSUE THREAD

**Issue by riturajkaushik** [Sylhare/Type-on-Strap#112] opened 2018-09-11 00:55 UTC
I tried to write the following equation in a post 
~~~
$$
P(w \mid D) = \frac{P(D \mid w)P(w)}{\int {P(D \mid w_i)dw_i}}
$$
~~~
But this equation is always left aligned and not centered.

This issue can be resolved by changing ```main.min.js``` as follows by sending a third parameter to ```katex.render(t,n,{displayMode: mode})``` which was initially ```katex.render(t,n) ```

~~~
var elements=document.getElementsByTagName("script");Array.prototype.forEach.call(elements,function(e){if(-1!==e.type.indexOf("math/tex")){var mode=false; var t=e.innerText||e.textContent;t=t.replace(/%.*/g,"");var n=document.createElement("span");-1!==e.type.indexOf("mode=display")?(n.className+="math-display", mode=true):(n.className+="math-inline", mode=false),katex.render(t,n,{displayMode: mode}),e.parentNode.insertBefore(n,e)}});try{var elem=document.querySelector(".grid"),msnry=new Masonry(elem,{itemSelector:".grid-item",columnWidth:".grid-sizer",gutter:".gutter-sizer",percentPosition:!0}),imgLoad=imagesLoaded(elem);imgLoad.on("progress",function(e,t){msnry.layout()})}catch(e){if(!(e instanceof ReferenceError))throw e}document.addEventListener("DOMContentLoaded",function(e){var t=document.getElementById("pull"),n=document.querySelector("nav ul");t.addEventListener("click",function(e){n.classList.toggle("hide")}),window.addEventListener("scroll",function(){var e=window.pageYOffset|document.body.scrollTop;document.getElementById("main").style.backgroundPosition="100% "+parseInt(-e/3)+"px, 0%, center top"})});
~~~

**Comment by Sylhare** [comment] 2018-09-13 14:35
Hi!

I think it was not centered by design, there's a katex.js that does the initialisation, I'll make some tries to see how it looks centered ;)

Thanks for the suggestion.

**Comment by Sylhare** [comment] 2018-09-13 18:00
So in order for the katex equation to be centered. You need indeed the `{displayMode: true}` as said in [#626](https://github.com/Khan/KaTeX/issues/626) that will enable a CSS rule that will center the equation.

However I don't want to implement that because the inline equation won't be supported anymore. What I can do is push with the option set to `false`, and you can pass it `true`.

**Closed** 2018-09-13 18:01 UTC
